collections:
  onhold:
    output: true
  past:
    output: true

defaults:
  - scope:
      path: ""
      type: "onhold"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "past"
    values:
      layout: "project"
  - scope:
      path: "_past/hackathon" 
      type: "past"
    values:
      hackathon: true