markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

collections:
  onhold:
    output: true
  past:
    output: true
  current:
    output: true

defaults:
  - scope:
      path: ""
      type: "onhold"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "past"
    values:
      layout: "project"
  - scope:
      path: "_past/hackathon" 
      type: "past"
    values:
      hackathon: "some place"
  - scope:
      path: ""
      type: "current"
    values:
      layout: "project"