collections:
  projects:
    output: true
  potentials:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "potentials"
    values:
      layout: "potential"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"